# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-16 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import django_state_machines.fields
import fields_tests.machines


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', django_state_machines.fields.StateMachineCharField(choices=[(b'accepted', b'Accepted state'), (b'not_accepted', b'Not accepted state'), (b'rejected', b'Rejected state')], default=b'accepted', handler=fields_tests.machines.ProductHandler, max_length=50)),
            ],
        ),
    ]
