# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-16 08:33
from __future__ import unicode_literals

from django.db import migrations
import django_state_machines.fields
import fields_tests.machines


class Migration(migrations.Migration):

    dependencies = [
        ('fields_tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='state',
            field=django_state_machines.fields.StateMachineCharField(choices=[(b'accepted', b'Accepted state'), (b'not_accepted', b'Not accepted state'), (b'rejected', b'Rejected state')], default=b'not_accepted', handler=fields_tests.machines.ProductHandler, max_length=50),
        ),
    ]
